algo_args:
  use_gae: True
  lambda: 1.0
  kl_coeff: 0.2
  batch_episode: 128
  num_sgd_iter: 10
  vf_loss_coeff: 1.0
  lr: 0.0005
  entropy_coeff: 0.01
  clip_param: 0.3
  vf_clip_param: 20.0
  batch_mode: "truncate_episodes"